sinatraを作成しました
satousi/memo_app pull request #1
Opened 2023-06-08 04:47 UTC by satousi

sinatraを作成しました
ご確認よろしくお願いします🙏

2023-06-14 13:23 UTC, u1tnk commented on memo.rb
> +def json_memo_read
語順的に  動詞、目的語の順の方が一般的だと思います。

2023-06-14 13:25 UTC, u1tnk commented on memo.rb
> +    @title += '<tr>'
htmlをcontroller(sinatraだとこのファイル)で生成するのは原則しません。 メモデータをerbに渡して表示するようにしましょう。

2023-06-14 13:25 UTC, u1tnk commented on memo.rb
> +  json_memos = json_memo_read
読み込むメソッドは良いですが、変数名にjsonが入っているのはおかしいです。memosだけで大丈夫です。

2023-06-14 13:26 UTC, u1tnk commented on memo.rb
> +  open('public/memo.json') do |file|
二回出てきてるちょっと長い文字列なので このパスは定数に入れた方が良いと思います。

2023-06-14 13:30 UTC, u1tnk commented on memo.rb
> +  title = CGI.escapeHTML(params[:title])
escapeするのは表示するときです。 escapeしたものを保存してしまうとデータが変更されてしまいます。

2023-06-14 13:31 UTC, u1tnk commented on memo.rb
> +  array_memos = json_memos.keys
array_memos だと メモの配列のように見えますが、実際はキーの配列なのでちょっとおかしいですね。

2023-06-14 13:34 UTC, u1tnk commented on memo.rb
> +  @title = json_memos[@key]['title']
erbに渡すインスタンス変数はファイルをまたぐので数が少ない方が把握しやすいので、`@memo = json_memos[@key]` とメモ単位で渡した 方が良いですね。

2023-06-15 05:59 UTC, satousi commented on memo.rb
> +def json_memo_read
了解しました🙌

2023-06-15 06:02 UTC, satousi commented on memo.rb
> +    @title += '<tr>'
了解しました。

2023-06-15 06:03 UTC, satousi commented on memo.rb
> +  json_memos = json_memo_read
了解しました。

2023-06-15 06:03 UTC, satousi commented on memo.rb
> +  open('public/memo.json') do |file|
了解しました。

2023-06-15 06:08 UTC, satousi commented on memo.rb
> +  @title = json_memos[@key]['title']
了解しました。

2023-06-15 06:57 UTC, satousi commented on memo.rb
> +  title = CGI.escapeHTML(params[:title])
>escapeするのは表示するときです

表示画面でおかしくなることを避けるのでhtmlで対策する必要があり、rubyだと内部になるから対策できてない🙌

2023-06-15 07:11 UTC, satousi commented on memo.rb
> +  array_memos = json_memos.keys
了解しました。

2023-06-16 02:47 UTC, u1tnk commented on memo.rb
> +  title = CGI.escapeHTML(params[:title])
補足すると 対策はできてるんですが、ここだと保存する前なので保存したデータが変更されてしまいます。
そうするとhtml表示する以外の用途に使うときに変換を戻す必要があったりするのでhtml用の変換は表示するときだけやるべきということです。

2023-06-16 03:06 UTC, u1tnk requested changes

2023-06-16 03:06 UTC, u1tnk commented on memo.rb
> +  array_keys = memos.keys
rubyでは array/listを使いません。 こちらであれば `keys`ですが、ちょっと不明確なので `memo_keys`が良いかなと思いました。

ただし、このぐらいの長さなら

`memos[memos.keys.max.to_i + 1] `

で良いかと思います。
何度も出てくるとか理解が難しいほど長いときに変数に入れるようにしましょう

2023-06-16 13:11 UTC, satousi commented on public/memo.json
データファイルはプログラムとして必要ですが開発にはいらないファイルとは、
全く気づきませんでした🙏

2023-06-16 13:12 UTC, satousi commented on .gitignore
> +.env
>多くのパターンが無視されているようですが自動生成されたものでしょうか？

どこかで拾ってきたファイルをそのままコピペして使用しました😓

2023-06-16 13:13 UTC, satousi commented on Gemfile
> +gem 'rubocop', require: false
ただ単にコピペして何も考えずにのせていました。
開発のみに使用しますということわりなのですね🙌

2023-06-16 13:14 UTC, satousi commented on README.md
> +## 動かすのに必要なライブラリ
了解です

2023-06-16 13:14 UTC, satousi commented on memo.rb
> +path = 'public/memo.json'
了解です

2023-06-16 13:15 UTC, satousi commented on memo.rb
> +  memos = { "0": { "title": 'ここはタイトル', "content": 'ここは内容' } }
>これは初期の空ファイルのときの為でしょうか？

空ファイルだとエラーになるのでエラーを避けようと試みました。

>こういう想定される処理は例外では無いので、例外を使わないようにしましょう。

了解です

>例外を使うとしても StandardErrorでは無くもっと限定された例外をrescueするようにしましょう。想定外の例外も拾ってしまうので。例外使わないので参考まで。

StandardErrorはrubocopのーAで作られたものをそのまま考えもせずに使用していました😓


>初期ファイルを作っていると思うのですが、なぜ実データが必要なのでしょうか？初期で作るにしても {}だけで良いと思います。

jsonファイルの形でなんらかのデータを記入作成しないといけない（エラーになる）と思い込んでいました😓

また先ほど気づいたのですが、そもそも

>初期はファイルは無しにしましょう。アクセスがあったらプログラムでファイルを作るようにしましょう。

これはmemo.jsonは存在させないということだったのですね😓
勝手な解釈で空ファイルの状態だと思い込んでいました。

さらに例外処理とか使用しましたが、wcコマンド作成時に教えてもらったempty?使えばよかったです😓

2023-06-16 13:18 UTC, satousi commented on memo.rb
> +  array_keys = memos.keys
>rubyでは array/listを使いません。 

https://u1tnk.github.io/blog/2022/12/04/naming_variable/
これもwcの時に教えていただいたブログに載っておりました😓

2023-06-18 16:49 UTC, u1tnk commented on .gitignore
> +.env
コピペするのも必要とは思いますが、理解できないものをそのまま使うのはNGです。
理解できる部分だけ使うようにしましょう。

2023-06-18 17:03 UTC, u1tnk requested changes

2023-06-18 17:03 UTC, u1tnk commented on memo.rb
> +patch '/memos/:key/changes' do
RESTでは  `PATCH /memos/:key` だけで更新の意図になるので changesは不要です。 削除の方も同様です。

2023-06-19 14:13 UTC, u1tnk approved these changes

2023-06-19 23:44 UTC, merged